ITIExamSystem/urls.py
from django.contrib import admin
from django.urls import path , include
from classroom.views import accounting,student,instructor,manager,subject
from django.conf import settings
from django.conf.urls.static import static

handler404 = accounting.handler404

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/',accounting.SignUpView.as_view() , name='signup'),
    path('accounts/signup/student/', student.StudentSignupView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', instructor.InstructorSignUpView.as_view(), name='instructor_signup'),
    path('accounts/signup/manager/', manager.ManagerSignUpView.as_view(), name='manager_signup'),
    path('accounts/signup/subject/', subject.subject_add, name='subject_add'),
    path('accounts/signup/showInformation/', manager.show_information, name='show_information'),
    path('accounts/signup/showInformation/student/', student.show_information_student, name='show_student_details'),
    path('accounts/signup/showInformation/student/delete/<int:pk>', student.delete_information_student,
         name='delete_student_details'),
    path('accounts/signup/showInformation/instructor/', instructor.show_information_instructor, name='show_instructor_details'),
    path('accounts/signup/showInformation/Instructor/delete/<int:pk>', instructor.delete_information_Instructor, name='delete_Instructor_details'),
    path('accounts/signup/showInformation/subject/', subject.show_information_subject, name='show_subject_details'),
    path('accounts/signup/showInformation/subject/delete/<int:pk>', subject.delete_subject_details, name='delete_subject_details'),
    path('accounts/signup/showInformation/subjectsStudents>', manager.add_subjects_to_students, name='add_subjects_students'),
    path('accounts/signup/student/profile', student.profile, name='student_profile'),
    path('accounts/signup/student/profile/edit', student.edit_profile, name='edit_student_profile'),
    path('accounts/signup/instructor/profile', instructor.profile, name='inst_profile'),
    path('accounts/signup/instructor/profile/edit', instructor.edit_profile, name='edit_instructor_profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/urls.py
from django.urls import path , include
from classroom.views import accounting,student,instructor
urlpatterns = [
    path('',accounting.home , name='home'),
    path('student/', include(([
                                   path('', student.SubjectListView.as_view(), name='exam_list'),
                                   path('exam/<int:subject_pk>', student.take_Exam, name='take_exam'),
                                   path('taken/', student.TakenExamListView.as_view(), name='taken_exam_list'),
                                   # path('quiz/<int:pk>/', student.take_quiz, name='take_quiz'),
                               ], 'classroom'), namespace='student')),

    path('instructor/', include(([
                                   path('', instructor.SubjectQustionsView.as_view(), name='subject_exam_list'),
                                   path('addqustion',instructor.Question_add ,name='qustion_add'),
                                   path('addQuestionAnswers/<int:question_pk>',instructor.Question_Answers_add , name='question_answers_add'),
                                   path('editQuestionAnswers/<int:question_pk>',instructor.Question_Answers_edit , name='question_answers_edit'),
                                   path('deleteQuestionAnswers/<int:question_pk>',instructor.Question_Answers_delete , name='question_answers_delete'),
                                    path('setdegree', instructor.set_subject_Exam_degree, name='Exam_degree'),
                                    path('taken',instructor.TakenExamListView.as_view() , name='taken_exam_list'),
                                    path('students',instructor.showStudents,name='students_show'),
                                    path('students/<int:student_pk>',instructor.showStudentExams,name='student_Exam_show'),
                               ], 'classroom'), namespace='instructor')),
]

classroom/views/accounting.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from classroom.decorators import manager_required

@method_decorator([login_required,manager_required] , name='dispatch')
class SignUpView(TemplateView):
    template_name = 'registration/signup.html'



def home(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            return redirect('student:exam_list')#student home page
        elif request.user.is_manager:
            return redirect('signup')#manger home page
        else:
            return redirect('instructor:subject_exam_list')#instractor home page
    return  render(request,'classroom/home.html')#home pag



def handler404(request,ex):
    return render(request, '404.html', status=404)

    
def handler500(request,ex):
    return render(request, '500.html', status=500)

classroom/views/instructor.py
from django.views.generic import CreateView ,ListView
from classroom.models import User,Question ,Answer,Subject ,Exam ,Instructor , Student
from classroom.forms import InstructorSignupForm , QuestionForm , BaseAnswerInlineFormSet
from django.contrib import messages
from django.shortcuts import redirect ,render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from classroom.decorators import instructor_required,manager_required
from django.core.paginator import Paginator
from django.db import transaction
from  django.shortcuts import get_object_or_404, reverse
from django.forms import inlineformset_factory
from django.http import JsonResponse , HttpResponse


@method_decorator([login_required,manager_required] , name='dispatch')
class InstructorSignUpView(CreateView):
    model = User
    form_class = InstructorSignupForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type']='add new Instuctor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user=form.save()
        messages.success(self.request, 'Done! ,  add new instructor successfully.... ')
        return redirect('instructor_signup')

@method_decorator([login_required,instructor_required],name='dispatch')
class SubjectQustionsView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'classroom/instructors/question_list.html'

    def get_queryset(self):
        quaryset=Question.objects.filter(subject=(self.request.user.instructor.subject or None))\
            .order_by('id').reverse()
        paginator = Paginator(quaryset, 25)  # Show 25 Question per page
        page = self.request.GET.get('page')
        quaryset = paginator.get_page(page)
        return quaryset


@login_required
@instructor_required
def Question_add(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.subject=request.user.instructor.subject
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('instructor:question_answers_add', question.pk)
    else:
        form = QuestionForm()

    return render(request, 'classroom/instructors/question_add_form.html', {'form': form})



@login_required
@instructor_required
def Question_Answers_add(request,question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('instructor:subject_exam_list')

    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'classroom/instructors/question_change_form.html', {
        'question': question,
        'form': form,
        'formset': formset
    })


@login_required
@instructor_required
def Question_Answers_edit(request,question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.reversesave()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('instructor:subject_exam_list')

    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'classroom/instructors/question_change_form.html', {
        'question': question,
        'form': form,
        'formset': formset
    })


@login_required
@instructor_required
def Question_Answers_delete(request, question_pk):
    if request.method == 'GET':
        Question.objects.filter(id=question_pk).delete()
        return JsonResponse({"success": True}, status=200)
    else:
        return HttpResponse ("Error in deleteing")




@login_required
@instructor_required
def set_subject_Exam_degree(request):
    subject= Subject.objects.get(instructor=request.user.instructor)
    if 1 < int(request.POST['difficult_num']) <= 14 \
        and 3 < (int(request.POST['ramining_num']) + \
            int(request.POST['understanding_num'])) <15 :
        subject.question_num_difficult=request.POST['difficult_num']
        subject.question_num_ramining=request.POST['ramining_num']
        subject.question_num_understanding=request.POST['understanding_num']
        subject.save()
        messages.success(request,"subject level updated")
    else:
        messages.warning(request, ' please , make sure number of questions is 15!!!!' )
    return redirect('instructor:subject_exam_list')



@method_decorator([login_required,instructor_required] , name='dispatch')
class TakenExamListView(ListView):
    model = Exam
    context_object_name = 'Exams'
    template_name = 'classroom/instructors/taken_quiz_list.html'

    def get_queryset(self):
        queryset = Exam.objects.filter(subject=self.request.user.instructor.subject)
        print(queryset)
        return queryset



@login_required
@instructor_required
def showStudents(request):
    students=request.user.instructor.subject.students.all()
    return render(request,'classroom/instructors/students_list.html',{'students':students})


@login_required
@instructor_required
def showStudentExams(request,student_pk):
    studentExams=Exam.objects.filter(student=student_pk)
    return render(request,'classroom/instructors/taken_quiz_list.html',{'Exams':studentExams})






@login_required
@manager_required
def show_information_instructor(request):
    Instructors = Instructor.objects.all()
    return render(request, 'admin/instructor_index.html',{'Instructors':Instructors})


@login_required
@manager_required
def delete_information_Instructor(request, pk):
    User.objects.get(pk=pk).delete()
    return JsonResponse({"success": True}, status=200)


@login_required
@instructor_required
def profile(request):
    context = {"name": request.user.username,
               "image": request.user.profile_pic.url,
               "country": request.user.country,
               "phone": request.user.phone,
               "birth_date": request.user.birth_date,
               "course" : request.user.instructor.subject,}
    return render(request, "classroom/students/profile.html", context)

@login_required
@instructor_required
def edit_profile(request):

    if request.method == 'POST':
        print(request.user)
        user = request.user
        user.username = request.POST['name']
        user.birth_date = request.POST['birth_date']
        user.country = request.POST['country']
        user.phone = request.POST['phone']
        if request.FILES:
            user.profile_pic = request.FILES['profile_pic']
        user.save()
        return redirect(reverse("inst_profile"))

classroom/views/manager.py
from django.views.generic import CreateView
from classroom.models import User ,Student,Subject
from django.shortcuts import redirect , render
from django.contrib.auth import login
from classroom.forms import ManagerSignUpForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from classroom.decorators import manager_required
from django.contrib import messages


@method_decorator([login_required,manager_required] , name='dispatch')
class ManagerSignUpView(CreateView):
    model = User
    form_class = ManagerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Signup as a Manager'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('signup')

@login_required
@manager_required
def add_subjects_to_students(request):
    if request.method== 'POST':
        students=Student.objects.filter(pk__in =request.POST.getlist('students'))
        subjects=Subject.objects.filter(pk__in =request.POST.getlist('subjects'))
        for student in students:
            for subject in subjects:
                student.subjects.add(subject)
                student.save()
        messages.success(request,'subjects were added sucussefly')
        return redirect('home')
    else:
        students=Student.objects.all()
        subjects=Subject.objects.all()
        return render(request,'admin/add_subjects_students.html',{
            'students':students,
            'subjects':subjects
        })

@login_required
@manager_required
def show_information(request):
    return render(request, 'admin/index.html')

classroom/views/subject.py
from django.views.generic import CreateView
from classroom.models import Subject
from classroom.forms import SubjectAddForm
from django.shortcuts import redirect , render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from classroom.decorators import manager_required
from django.http import JsonResponse

@login_required
@manager_required
def subject_add(request):
    if request.method == 'POST':
        print("============",request.POST)
        subjectForm=SubjectAddForm(request.POST)
        if subjectForm.is_valid():
            subjectForm.save()
            messages.success(request, 'add new subject successfully.......')
            return redirect('subject_add')
        else:
            messages.error(request, 'error in adding new subject .......')
            return redirect('subject_add')
    else:
        return render(request,'registration/signup_form.html',{
            'form':SubjectAddForm ,'user_name': 'Subject'
        })


@login_required
@manager_required
def show_information_subject(request):
    subjects = Subject.objects.all()
    return render(request, 'admin/subject_index.html', {'subjects':subjects})


@login_required
@manager_required
def delete_subject_details(request, pk):
    Subject.objects.get(pk=pk).delete()
    return JsonResponse({"success": True}, status=200)

classroom/templates/classroom/instructors/_header.html
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'instructor:subject_exam_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'instructor:taken_exam_list'  %}">Taken</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'students' %} active{% endif %}" href="{% url 'instructor:students_show' %}">Students</a>
  </li>
</ul>

classroom/templates/classroom/instructors/create_Exam.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>hello exam</h1>
{% endblock %}

classroom/templates/classroom/instructors/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="row mt-5 mb-5">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
                </ol>
            </nav>
        </div>
        <div class="col-12">
            <h2 class="mb-3 text-center h1">Add a new question</h2>
            <p class="lead">Add first the text of the question. In the next step you will be able to
                add the possible answers.</p>
        </div>
        <div class="col-8">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-lg">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

classroom/templates/classroom/instructors/question_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags crispy_forms_filters %}
{% block content %}
    <div class="row mt-5 mb-5">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
                </ol>
            </nav>
        </div>
        <div class="col-12">
            <h2 class="mb-3 text-center">{{ question.txt }}</h2>
        </div>
        <div class="col-8">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ formset.management_form }}
                {{ form|crispy }}
                <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-8">
                                <strong style="color: #000000;">Answers</strong>
                            </div>
                            <div class="col-2">
                                <strong>Correct?</strong>
                            </div>
                            {% if form.instance.pk %}
                                <div class="col-2">
                                    <strong>Delete?</strong>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    {% for error in formset.non_form_errors %}
                        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
                    {% endfor %}
                    <div class="list-group list-group-flush list-group-formset">
                        {% for form in formset %}
                            <div class="list-group-item">
                                <div class="row">
                                    <div class="col-8">
                                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                                        {{ form.text|as_crispy_field }}
                                        {% if form.instance.pk and form.text.value != form.instance.text %}
                                            <p class="mb-0 mt-1">
                                                <small class="text-muted font-italic"><strong>Old
                                                    answer:</strong> {{ form.instance.text }}</small>
                                            </p>{% endif %}
                                    </div>
                                    <div class="col-2">
                                        {{ form.is_correct }}
                                    </div>
                                    <div class="col-2">
                                        {% if form.instance.pk %}
                                            {{ form.DELETE }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <p>
                    <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and
                        maximum
                        <strong>10</strong> answers. Select at least one correct answer.
                    </small>
                </p>
                <button type="submit" class="btn btn-success">Save changes</button>
            </form>
        </div>
    </div>
{% endblock %}

classroom/templates/classroom/instructors/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="row mt-5 mb-5">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a>
                    </li>
                    <li class="breadcrumb-item"><a
                            href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
                </ol>
            </nav>
        </div>
        <div class="col-12">
            <h2 class="mb-3 text-center">Confirm deletion</h2>
            <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There
                is no
                going back.</p>
        </div>
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
                <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-secondary btn-lg"
                   role="button">Nevermind</a>
            </form>
        </div>
    </div>
{% endblock %}

classroom/templates/classroom/instructors/question_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row mt-5 mb-5">
    <div class="col-12">
        {% include 'classroom/instructors/_header.html' with active='new' %}
    </div>
         {% if request.user.instructor.subject %}
    <div class="row mb-2">
        <div class="col-12">
            <form METHOD="post"  ACTION="{% url 'instructor:Exam_degree' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="QuestionDifficultNum">difficult Questions number</label>
                    <input type="number" class="form-control" id="QuestionDifficultNum"  name="difficult_num" value='{{ request.user.instructor.subject.question_num_difficult}}'  placeholder="question number">
                </div>

                <div class="form-group">
                    <label for="QuestionUnderstandingNum">Understanding Questions number</label>
                    <input type="number" class="form-control" id="QuestionUnderstandingNum" name="understanding_num"  value='{{ request.user.instructor.subject.question_num_understanding}}'  placeholder="question number">
                </div>

                <div class="form-group">
                    <label for="QuestionRaminingNum"> remining Questions number </label>
                    <input type="number" class="form-control" id="QuestionRaminingNum" name="ramining_num"  value='{{ request.user.instructor.subject.question_num_ramining}}'  placeholder="question number">
                </div>
                <input type="submit" class="btn btn-primary align-content-end mb-2" value="update"/>
            </form>
        </div>
        <div class="col-4">
             <a href="{% url 'student:take_exam' request.user.instructor.subject.id %}"
                class="btn btn-success mb-2">show Exam simple</a>
        </div>
        <div class="col-4">
             <a href="{% url 'instructor:qustion_add' %}"
                class="btn btn-danger mb-2">Add question</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">

            <table class="table table-hover table-bordered">
                <tr>
                    <th>Question text</th>
                    <th>Question difficulty</th>
                    <th>Question type</th>
                    <th>Question Chapter</th>
                    <th colspan="2">option</th>
                </tr>

                {% for question in questions %}
                    <tr>
                        <td>{{ question.text|upper }}
                        </td>
                        <td>{%if question.difficulty == 1 %}difficult{% else %}simple{% endif %}
                        </td>
                        <td>{%if question.objective == 1 %}ramining{% elif question.objective == 2 %}undestanding{%else%}creativety{% endif %}
                        </td>
                        <td>{{ question.chapter_num|upper }}
                        </td>
                        <td>
                            <a class="btn btn-success" href="{% url 'instructor:question_answers_edit' question.pk %}">Edit</a>
                        </td>

                        <td class="m-4">
                            <button type="submit" value="Delete" id="{{ question.pk }}" class="btn btn-danger">delete
                            </button>
                        </td>

                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>

    <div class="pagination m-auto">
        <span class="step-links">
            {% if questions.has_previous %}
                <a class="btn btn-secondary" href="?page=1">&laquo; first</a>
                <a class="btn btn-danger" href="?page={{ questions.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current btn btn-primary">
                Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
            </span>

            {% if questions.has_next %}
                <a class="btn btn-success" href="?page={{ questions.next_page_number }}">next</a>
                <a class="btn btn-secondary" href="?page={{ questions.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

        {% else %}
         <p>there is An Error . please contact your manger to update the situation .</p>

        {% endif %}

    <script type="text/javascript">
        let table = document.getElementsByTagName("table")[0],
            ajax = new XMLHttpRequest();

        table.onclick = function (event) {
            if (event.target.tagName == "BUTTON") {
                row = event.target.parentElement.parentElement;
                ajax.open("GET", "http://localhost:8000/instructor/deleteQuestionAnswers/" + event.target.id);
                ajax.send();
                ajax.onreadystatechange = () => {
                    if (ajax.readyState === 4 && ajax.status === 200) {
                        response = JSON.parse(ajax.responseText);
                        console.log(response);
                        if (response.success) {
                            row.remove();

                        } else {
                            flash.innerHTML = "<p class='alert alert-danger'>" + data.msg + "</p>";

                        }
                        // if(response['msg']== "done")
                        // row.remove();
                    }
                }

            }
        }


    </script>
{% endblock %}

classroom/templates/classroom/instructors/quiz_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new quiz</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new quiz</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>
{% endblock %}

classroom/templates/classroom/instructors/students_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-5 mb-5">
        <div class="col-12">
            {% include 'classroom/instructors/_header.html' with active='students' %}
        </div>
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>name</th>
                        <th>exams</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in students %}
                        <tr>
                            <td>{{ student }}</td>
                            <td>
                                <a class="btn btn-success" href="{% url 'instructor:student_Exam_show' student.pk  %}">show Score </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class=" alert alert-warning text-center" colspan="3">
                                there is any student join your Subject
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}