ITIExamSystem/urls.py
from django.contrib import admin
from django.urls import path , include
from classroom.views import accounting,student,instructor,manager,subject
from django.conf import settings
from django.conf.urls.static import static

handler404 = accounting.handler404

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/',accounting.SignUpView.as_view() , name='signup'),
    path('accounts/signup/student/', student.StudentSignupView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', instructor.InstructorSignUpView.as_view(), name='instructor_signup'),
    path('accounts/signup/manager/', manager.ManagerSignUpView.as_view(), name='manager_signup'),
    path('accounts/signup/subject/', subject.subject_add, name='subject_add'),
    path('accounts/signup/showInformation/', manager.show_information, name='show_information'),
    path('accounts/signup/showInformation/student/', student.show_information_student, name='show_student_details'),
    path('accounts/signup/showInformation/student/delete/<int:pk>', student.delete_information_student,
         name='delete_student_details'),
    path('accounts/signup/showInformation/instructor/', instructor.show_information_instructor, name='show_instructor_details'),
    path('accounts/signup/showInformation/Instructor/delete/<int:pk>', instructor.delete_information_Instructor, name='delete_Instructor_details'),
    path('accounts/signup/showInformation/subject/', subject.show_information_subject, name='show_subject_details'),
    path('accounts/signup/showInformation/subject/delete/<int:pk>', subject.delete_subject_details, name='delete_subject_details'),
    path('accounts/signup/showInformation/subjectsStudents>', manager.add_subjects_to_students, name='add_subjects_students'),
    path('accounts/signup/student/profile', student.profile, name='student_profile'),
    path('accounts/signup/student/profile/edit', student.edit_profile, name='edit_student_profile'),
    path('accounts/signup/instructor/profile', instructor.profile, name='inst_profile'),
    path('accounts/signup/instructor/profile/edit', instructor.edit_profile, name='edit_instructor_profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/urls.py
from django.urls import path , include
from classroom.views import accounting,student,instructor
urlpatterns = [
    path('',accounting.home , name='home'),
    path('student/', include(([
                                   path('', student.SubjectListView.as_view(), name='exam_list'),
                                   path('exam/<int:subject_pk>', student.take_Exam, name='take_exam'),
                                   path('taken/', student.TakenExamListView.as_view(), name='taken_exam_list'),
                                   # path('quiz/<int:pk>/', student.take_quiz, name='take_quiz'),
                               ], 'classroom'), namespace='student')),

    path('instructor/', include(([
                                   path('', instructor.SubjectQustionsView.as_view(), name='subject_exam_list'),
                                   path('addqustion',instructor.Question_add ,name='qustion_add'),
                                   path('addQuestionAnswers/<int:question_pk>',instructor.Question_Answers_add , name='question_answers_add'),
                                   path('editQuestionAnswers/<int:question_pk>',instructor.Question_Answers_edit , name='question_answers_edit'),
                                   path('deleteQuestionAnswers/<int:question_pk>',instructor.Question_Answers_delete , name='question_answers_delete'),
                                    path('setdegree', instructor.set_subject_Exam_degree, name='Exam_degree'),
                                    path('taken',instructor.TakenExamListView.as_view() , name='taken_exam_list'),
                                    path('students',instructor.showStudents,name='students_show'),
                                    path('students/<int:student_pk>',instructor.showStudentExams,name='student_Exam_show'),
                               ], 'classroom'), namespace='instructor')),
]

classroom/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator,MaxValueValidator,ValidationError
from django.utils.html import escape,mark_safe
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now

# Create your models here.
class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    phone = models.CharField(max_length=15, null=True)
    country = models.CharField(default='Egypt', blank=True, null=True, max_length=50)
    birth_date = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to="profile_pics", default="profile_pics/default.jpg")

class Subject(models.Model):
    name=models.CharField(max_length=50 , unique = True)
    color = models.CharField(max_length=7,default='#007bff')
    value = models.FloatField(
        default=0.5,
        validators=[MinValueValidator(0.3), MaxValueValidator(0.8)]
    )
    question_num_difficult=models.IntegerField(
        default=1
    )
    question_num_understanding=models.IntegerField(
        default=1
    )
    question_num_ramining=models.IntegerField(
        default=1
    )
    chapter_num=models.IntegerField(
        default=1
    )




    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    subjects = models.ManyToManyField(Subject,related_name='students')

    def __str__(self):
        return self.user.username

class Instructor(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    subject = models.OneToOneField(Subject,on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.user.username


class Question(models.Model):
    text=models.CharField('Question',max_length=255)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,related_name='questions')
    value = models.FloatField(
        default=0.5,
        validators=[MinValueValidator(0.3), MaxValueValidator(0.8)]
    )
    difficulty_level=(
        (1,'difficult'),
        (2,'simple')
    )
    objective_level=(
        (1,'remining'),
        (2,'understanding'),
        (3,'creative'),
    )
    difficulty=models.IntegerField(
        choices=difficulty_level,
        default=1
    )
    # 1 ----> simple
    # 2 -----> difficult
    objective=models.IntegerField(
        choices=objective_level,
        default=1
    )

    def get_objective_level(self):
        return self.objective_level[self.objective][1]


    def get_difficulty_level(self):
        return self.difficulty_level[self.difficulty][1]


    def get_chapter_num(self):
        return self.subject.chapter_num
    # 1 ---> ramining
    # 2 ---> udestanding
    # 3 ----> creativety

    chapter_num=models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(4)
        ]
    )



    def clean(self):
        if self.value < 0:
            raise ValidationError(_('Only numbers equal to 1 or greater are accepted.'))

    def __str__(self):
        return self.text



class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='answers')
    text = models.CharField('Answer',max_length=255)
    is_correct =models.BooleanField('Correct answer',default=False)

    def __str__(self):
        return self.text



class Exam(models.Model):
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,related_name='exams')
    student = models.ForeignKey(Student,on_delete=models.CASCADE,related_name='exams')
    score = models.FloatField()
    data= models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return (""+self.subject.name+" exam To Student : "+self.student.user.username)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE,related_name='exam_answers')
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE,related_name='+')



class Event(models.Model):
    title = models.CharField(max_length=200)
    data = models.DateTimeField(default=now())
    position =models.CharField(max_length=200)

classroom/views/accounting.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from classroom.decorators import manager_required

@method_decorator([login_required,manager_required] , name='dispatch')
class SignUpView(TemplateView):
    template_name = 'registration/signup.html'



def home(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            return redirect('student:exam_list')#student home page
        elif request.user.is_manager:
            return redirect('signup')#manger home page
        else:
            return redirect('instructor:subject_exam_list')#instractor home page
    return  render(request,'classroom/home.html')#home pag



def handler404(request,ex):
    return render(request, '404.html', status=404)

    
def handler500(request,ex):
    return render(request, '500.html', status=500)

classroom/views/instructor.py
from django.views.generic import CreateView ,ListView
from classroom.models import User,Question ,Answer,Subject ,Exam ,Instructor , Student
from classroom.forms import InstructorSignupForm , QuestionForm , BaseAnswerInlineFormSet
from django.contrib import messages
from django.shortcuts import redirect ,render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from classroom.decorators import instructor_required,manager_required
from django.core.paginator import Paginator
from django.db import transaction
from  django.shortcuts import get_object_or_404, reverse
from django.forms import inlineformset_factory
from django.http import JsonResponse , HttpResponse


@method_decorator([login_required,manager_required] , name='dispatch')
class InstructorSignUpView(CreateView):
    model = User
    form_class = InstructorSignupForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type']='add new Instuctor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user=form.save()
        messages.success(self.request, 'Done! ,  add new instructor successfully.... ')
        return redirect('instructor_signup')

@method_decorator([login_required,instructor_required],name='dispatch')
class SubjectQustionsView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'classroom/instructors/question_list.html'

    def get_queryset(self):
        quaryset=Question.objects.filter(subject=(self.request.user.instructor.subject or None))\
            .order_by('id').reverse()
        paginator = Paginator(quaryset, 25)  # Show 25 Question per page
        page = self.request.GET.get('page')
        quaryset = paginator.get_page(page)
        return quaryset


@login_required
@instructor_required
def Question_add(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.subject=request.user.instructor.subject
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('instructor:question_answers_add', question.pk)
    else:
        form = QuestionForm()

    return render(request, 'classroom/instructors/question_add_form.html', {'form': form})



@login_required
@instructor_required
def Question_Answers_add(request,question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('instructor:subject_exam_list')

    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'classroom/instructors/question_change_form.html', {
        'question': question,
        'form': form,
        'formset': formset
    })


@login_required
@instructor_required
def Question_Answers_edit(request,question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.reversesave()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('instructor:subject_exam_list')

    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)
    return render(request, 'classroom/instructors/question_change_form.html', {
        'question': question,
        'form': form,
        'formset': formset
    })


@login_required
@instructor_required
def Question_Answers_delete(request, question_pk):
    if request.method == 'GET':
        Question.objects.filter(id=question_pk).delete()
        return JsonResponse({"success": True}, status=200)
    else:
        return HttpResponse ("Error in deleteing")




@login_required
@instructor_required
def set_subject_Exam_degree(request):
    subject= Subject.objects.get(instructor=request.user.instructor)
    if 1 < int(request.POST['difficult_num']) <= 14 \
        and 3 < (int(request.POST['ramining_num']) + \
            int(request.POST['understanding_num'])) <15 :
        subject.question_num_difficult=request.POST['difficult_num']
        subject.question_num_ramining=request.POST['ramining_num']
        subject.question_num_understanding=request.POST['understanding_num']
        subject.save()
        messages.success(request,"subject level updated")
    else:
        messages.warning(request, ' please , make sure number of questions is 15!!!!' )
    return redirect('instructor:subject_exam_list')



@method_decorator([login_required,instructor_required] , name='dispatch')
class TakenExamListView(ListView):
    model = Exam
    context_object_name = 'Exams'
    template_name = 'classroom/instructors/taken_quiz_list.html'

    def get_queryset(self):
        queryset = Exam.objects.filter(subject=self.request.user.instructor.subject)
        print(queryset)
        return queryset



@login_required
@instructor_required
def showStudents(request):
    students=request.user.instructor.subject.students.all()
    return render(request,'classroom/instructors/students_list.html',{'students':students})


@login_required
@instructor_required
def showStudentExams(request,student_pk):
    studentExams=Exam.objects.filter(student=student_pk)
    return render(request,'classroom/instructors/taken_quiz_list.html',{'Exams':studentExams})






@login_required
@manager_required
def show_information_instructor(request):
    Instructors = Instructor.objects.all()
    return render(request, 'admin/instructor_index.html',{'Instructors':Instructors})


@login_required
@manager_required
def delete_information_Instructor(request, pk):
    User.objects.get(pk=pk).delete()
    return JsonResponse({"success": True}, status=200)


@login_required
@instructor_required
def profile(request):
    context = {"name": request.user.username,
               "image": request.user.profile_pic.url,
               "country": request.user.country,
               "phone": request.user.phone,
               "birth_date": request.user.birth_date,
               "course" : request.user.instructor.subject,}
    return render(request, "classroom/students/profile.html", context)

@login_required
@instructor_required
def edit_profile(request):

    if request.method == 'POST':
        print(request.user)
        user = request.user
        user.username = request.POST['name']
        user.birth_date = request.POST['birth_date']
        user.country = request.POST['country']
        user.phone = request.POST['phone']
        if request.FILES:
            user.profile_pic = request.FILES['profile_pic']
        user.save()
        return redirect(reverse("inst_profile"))

classroom/templates/classroom/students/_header.html
<h2 class="h1 text-center">Quizzes</h2>

<p class="lead h2" style="color: #FFFFFF;">
  Subjects:{% for subject in user.student.subjects.all %} {{ subject.get_html_badge }}{% endfor %}
</p>

<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'student:exam_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'student:taken_exam_list' %}">Taken</a>
  </li>
</ul>

classroom/templates/classroom/students/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}

classroom/templates/classroom/students/profile.html
{% extends 'base.html' %}

{% block content %}
    <br/><br/><br/>
    <h2 class="text-center">
        Your Profile Mr : {{ name }}
    </h2>
    <br/><br/><br/>
    <div class="container mb-5">
        <div id="home">
            <div class="row">
                <div class="col-xs-12 col-sm-9">
                    <div class="profile-user-info">
                        <div class="profile-info-row">
                            <div class="profile-info-name d-inline"><i class="fa fa-user-o light-orange bigger-110"></i> Username : </div>
                            <div class="profile-info-value d-inline">
                                <span>{{ name }}</span>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="profile-user-info">
                        <div class="profile-info-row">
                            <div class="profile-info-name d-inline"><i class="fa fa-birthday-cake light-orange bigger-110"></i> Birth Date : </div>
                            <div class="profile-info-value d-inline">
                                <span>{{ birth_date }}</span>
                            </div>
                        </div>
                        <hr />
                        <div class="profile-info-row">
                            <div class="profile-info-name d-inline"><i class="fa fa-phone-square light-orange bigger-110"></i> Phone Number : </div>

                            <div class="profile-info-value d-inline">
                                <span>{{ phone }}</span>
                            </div>
                        </div>
                        <hr />
                        <div class="profile-info-row">
                            <div class="profile-info-name d-inline"><i class="fa fa-map-marker light-orange bigger-110"></i> Location : </div>
                            <div class="profile-info-value d-inline">
                                <span>{{ country }}</span>
                            </div>
                        </div>
                        <hr />
                        <div class="profile-info-row">
                            <div class="profile-info-name">
                                <i class="middle ace-icon fa fa-facebook-square bigger-150 blue"></i>
                                <i class="middle ace-icon fa fa-twitter-square bigger-150 blue"></i>
                                <i class="middle ace-icon fa fa-google-plus-square bigger-150 blue"></i>
                            </div>
                        </div>
                        <hr />
                    </div>
                </div><!-- /.col-9 -->
                <div class="col-xs-12 col-sm-3">
                    <div class="profile-info-name text-center">Your Avater</div>
                    <br />
                    <span class="profile-picture">
                        <img class="editable img-responsive img-thumbnail" style="border-radius: 50%;" alt=" Avatar" id="avatar2" src="{{ image }}"
                             width="200px" height="200px">
                    </span>
                </div><!-- /.col-3 -->
            </div><!-- /.row -->
            {% if user.is_authenticated %}
                {% if user.is_student %}
                    <div class="row">
                        <h2 class="text-center">Cources</h2>
                        <div class="col-12">
                            <div class="col-4">
                                {% for subject in courses %}
                                    <p class="font-weight-bold bg-primary p-2"> {{ subject.name }}</p>
                                    <hr />
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% elif user.is_instructor %}
                     <div class="row mb-5">
                        <h2 class="text-center">Cource</h2>
                        <div class="col-12">
                            <div class="col-4">
                                <p class="font-weight-bold bg-danger p-2">{{ course.name }}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
            <div class="row justify-content-center">
                <div class="col-6">
                    <button type="button" class="btn btn-sm btn-block btn-success"
                            data-toggle="modal"
                            data-target="#edit-profile-modal">
                        <i class="ace-icon fa fa-plus-circle bigger-120"></i>
                        <span class="bigger-110">edit</span>
                    </button>
                    <div class="modal fade" id="edit-profile-modal" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document"
                             style="background-color:#161515">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle"
                                        style="color:#ffa101">Profile</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                {% if user.is_authenticated %}
                                    {% if user.is_student %}
                                        <form method="POST"
                                              action="{% url 'edit_student_profile' %}"
                                              enctype="multipart/form-data">
                                    {% elif user.is_instructor %}
                                        <form method="POST"
                                              action="{% url 'edit_instructor_profile' %}"
                                              enctype="multipart/form-data">
                                    {% endif %}
                                {% endif %}
                                <div class="modal-body">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_profile_pic" style="color:#ffa101">Profile
                                            pic:</label>
                                        <input type="file" name="profile_pic" accept="image/*"
                                               id="id_profile_pic" class="form-control"
                                               value="{{ image }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="id_name" style="color:#ffa101">User Name</label>
                                        <input type="text" name="name" maxlength="30" id="id_name"
                                               class="form-control" value="{{ name }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="id_phone" style="color:#ffa101">Phone:</label>
                                        <input type="text" name="phone" maxlength="15" id="id_phone"
                                               class="form-control" value="{{ phone }}">
                                    </div>


                                    <div class="form-group">
                                        <label for="id_country"
                                               style="color:#ffa101">Country:</label>
                                        <input type="text" name="country" maxlength="15"
                                               id="id_country"
                                               class="form-control" value="{{ country }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="id_birth_date" style="color:#ffa101">Birth
                                            date:</label>
                                        <input type="date" value="2000-01-01" name="birth_date"
                                               id="id_birth_date"
                                               class="form-control" value="{{ birth_date }}">
                                    </div>

                                </div>

                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">Save changes
                                    </button>
                                    <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Close
                                    </button>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
                </div>
            </div>
        </div>
    </div>
    </div><!-- /#home -->
{% endblock %}

classroom/templates/classroom/students/quiz_list.html
{% extends 'base.html' %}

{% block content %}
    <div style="background-color: #d8841c;" class="row mt-5 mb-5">
        <div class="col-12">
            {% include 'classroom/students/_header.html' with active='new' %}
        </div>
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>Quiz</th>
                        <th>Subject</th>
                        <th>Length</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for quiz in quizzes %}
                        <tr>
                            <td>{{ quiz.name }}</td>
                            <td>{{ quiz.subject.get_html_badge }}</td>
                            <td>{{ quiz.questions_count }} questions</td>
                            <td colspan="2">
                                <a
                                   href="{% url 'students:take_quiz' quiz.pk %}"
                                   class="btn btn-primary">Start quiz</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="bg-light text-center font-italic" colspan="4">No quiz matching your interests
                                right
                                now.
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

classroom/templates/classroom/students/subject_list.html
{% extends 'base.html' %}

{% block content %}
    <div style="background-color: #d8841c;" class="row mt-5 mb-5">
        <div class="col-12">
            {% include 'classroom/students/_header.html' with active='new' %}
        </div>
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>Subject</th>
                        <th>Exam</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for subject in subjects %}
                        <tr>
                            <td>{{ subject.name }}</td>
                            <td><a class="btn btn-primary"
                                   href="{% url 'student:take_exam' subject.id %}">Take Exam</a></td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="bg-light text-center font-italic" colspan="2">No quiz matching your interests
                                right now.
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}